INSERT INTO oiseaux (nom, espece, details)
	VALUES (	
		("Bergeronnette grise","Motacilla alba","plus d'information"),
		("Bruant Jaune","Emberiza citrinella","plus d'information"),
		("Mésange bleue","Cyanistes caeruleus","plus d'information"),
		("Moineau domestique","Passer domesticus","details":"plus d'information"),
		("Merle noir","Turdus merula","details":"plus d'information"),
		("Rougegorge familier","Erithacus rubecula","details":"plus d'information"),
		("Pie bavarde","Pica pica","details":"plus d'information"),
		("Pinson des arbres","Fringilla coelebs","details":"plus d'information"),
		("Tourterelle turque","Streptopelia decaocto","details":"plus d'information"),
		("Corneille noire","Corvus corone","details":"plus d'information"),
		("Pigeon ramier","Columba palumbus","details":"plus d'information"),
		("Accenteur mouchet","Prunella modularis","details":"plus d'information"),
		("Etourneau sansonnet","Sturnus vulgaris","details":"plus d'information"),
		("Verdier d'Europe","Chloris chloris","details":"plus d'information"),
		("Geai des chênes","Garrulus glandarius","details":"plus d'information"),
		("Pic épeiche","Dendrocopos major","details":"plus d'information"),
		("Troglodyte mignon","Troglodytes troglodytes","details":"plus d'information"),
		("Mésange nonnette","Poecile palustris","details":"plus d'information"),
		("Mésange noire","Periparus ater","details":"plus d'information"),
		("Sittelle torchepot","Sitta europaea","details":"plus d'information"),
		("Moineau friquet","Passer montanus","details":"plus d'information"),
		("Mésange à longue queue","Aegithalos caudatus","details":"plus d'information"),
		("Mésange huppée","Lophophanes cristatus","details":"plus d'information"),
		("Pic vert","Picus viridis","details":"plus d'information"),
		("Grive musicienne","Turdus philomelos","details":"plus d'information"),
		("Pinson du Nord","Fringilla montifringilla","details":"plus d'information"),
		("Tarin des aulnes","Spinus spinus","details":"plus d'information"),
		("Gros-bec casse-noyaux","Coccothraustes coccothraustes","details":"plus d'information"),
		("Bouvreuil pivoine","Pyrrhula pyrrhula","details":"plus d'information"),
		("Perruche à collier","Psittacula krameri","details":"plus d'information"),
		("Choucas des tours","Coloeus monedula","details":"plus d'information"),
		("Héron cendré","Ardea cinerea","details":"plus d'information"),
		("Buse variable","Buteo buteo","details":"plus d'information"),
		("Grimpereau des jardins","Certhia brachydactyla","details":"plus d'information"),
		("Epervier d'Europe","Accipiter nisus","details":"plus d'information"),
		("Faisan de Colchide","Phasianus colchicus","details":"plus d'information"),
		("Mouette rieuse","Chroicocephalus ridibundus","details":"plus d'information"),
		("Grive litorne","Turdus pilaris","details":"plus d'information"),
		("Faucon crécerelle","Falco tinnunculus","details":"plus d'information"),
		("Chardonneret élégant","Carduelis carduelis","details":"plus d'information"),
		("Roitelet huppé","Regulus regulus","details":"plus d'information"),
		("Corbeau freux","Corvus frugilegus","details":"plus d'information"),
		("Pic épeichette","Dryobates minor","details":"plus d'information"),
		("Pigeon biset","Columba livia","details":"plus d'information"),
		("Roitelet triple-bandeau","Regulus ignicapilla","details":"plus d'information"),
		("Gallinule poule-d'eau","Gallinula chloropus","details":"plus d'information"),
		("Mésange boréale","Poecile montanus","details":"plus d'information"),
		("Grive mauvis","Turdus iliacus","details":"plus d'information"),
		("Martin-pêcheur","Alcedo atthis","details":"plus d'information"),
		("Grive draine","Turdus viscivorus","details":"plus d'information"),
		("Fauvette à tête noire","Sylvia atricapilla","details":"plus d'information"),
		("Grande aigrette","Ardea alba","details":"plus d'information"),
		("Pic mar","Dendrocoptes medius","details":"plus d'information"),
		("Canard colvert","Anas platyrhynchos","details":"plus d'information"),
		("Pouillot véloce","Phylloscopus collybita","details":"plus d'information"),
		("Chevêche d'Athéna","Athene noctua","details":"plus d'information"),
		("Effraie des clochers","Tyto alba","details":"plus d'information"),
		("Chouette hulotte","Strix aluco","details":"plus d'information"),
		("Rougequeue noir","Phoenicurus ochruros","details":"plus d'information"),
		("Linotte mélodieuse","Linaria cannabina","details":"plus d'information"),
		("Bec-croisé des sapins","Loxia curvirostra","details":"plus d'information"),
		("Jaseur boréal","Bombycilla garrulus","details":"plus d'information"),
		("Perdrix grise","Perdix perdix","details":"plus d'information"),
		("Pic noir","Dryocopus martius","details":"plus d'information"),
		("Bergeronnette des ruisseaux","Motacilla cinerea","details":"plus d'information"),
		("Serin cini","Serinus serinus","details":"plus d'information"),
		("Pigeon colombin","Columba oenas","details":"plus d'information"),
		("Hibou moyen-duc","Asio otus","details":"plus d'information"),
		("Sizerin cabaret","Acanthis cabaret","details":"plus d'information"),
	)
