INSERT INTO oiseaux (nom, espece, details)
	VALUES (
		("Bergeronnette grise","Motacilla alba","plus d'information"),
		("Bruant Jaune","Emberiza citrinella","plus d'information"),
		("Mésange bleue","Cyanistes caeruleus","plus d'information"),
		("Moineau domestique","Passer domesticus","plus d'information"),
		("Merle noir","Turdus merula","plus d'information"),
		("Rougegorge familier","Erithacus rubecula","plus d'information"),
		("Pie bavarde","Pica pica","plus d'information"),
		("Pinson des arbres","Fringilla coelebs","plus d'information"),
		("Tourterelle turque","Streptopelia decaocto","plus d'information"),
		("Corneille noire","Corvus corone","plus d'information"),
		("Pigeon ramier","Columba palumbus","plus d'information"),
		("Accenteur mouchet","Prunella modularis","plus d'information"),
		("Etourneau sansonnet","Sturnus vulgaris","plus d'information"),
		("Verdier d'Europe","Chloris chloris","plus d'information"),
		("Geai des chênes","Garrulus glandarius","plus d'information"),
		("Pic épeiche","Dendrocopos major","plus d'information"),
		("Troglodyte mignon","Troglodytes troglodytes","plus d'information"),
		("Mésange nonnette","Poecile palustris","plus d'information"),
		("Mésange noire","Periparus ater","plus d'information"),
		("Sittelle torchepot","Sitta europaea","plus d'information"),
		("Moineau friquet","Passer montanus","plus d'information"),
		("Mésange à longue queue","Aegithalos caudatus","plus d'information"),
		("Mésange huppée","Lophophanes cristatus","plus d'information"),
		("Pic vert","Picus viridis","plus d'information"),
		("Grive musicienne","Turdus philomelos","plus d'information"),
		("Pinson du Nord","Fringilla montifringilla","plus d'information"),
		("Tarin des aulnes","Spinus spinus","plus d'information"),
		("Gros-bec casse-noyaux","Coccothraustes coccothraustes","plus d'information"),
		("Bouvreuil pivoine","Pyrrhula pyrrhula","plus d'information"),
		("Perruche à collier","Psittacula krameri","plus d'information"),
		("Choucas des tours","Coloeus monedula","plus d'information"),
		("Héron cendré","Ardea cinerea","plus d'information"),
		("Buse variable","Buteo buteo","plus d'information"),
		("Grimpereau des jardins","Certhia brachydactyla","plus d'information"),
		("Epervier d'Europe","Accipiter nisus","plus d'information"),
		("Faisan de Colchide","Phasianus colchicus","plus d'information"),
		("Mouette rieuse","Chroicocephalus ridibundus","plus d'information"),
		("Grive litorne","Turdus pilaris","plus d'information"),
		("Faucon crécerelle","Falco tinnunculus","plus d'information"),
		("Chardonneret élégant","Carduelis carduelis","plus d'information"),
		("Roitelet huppé","Regulus regulus","plus d'information"),
		("Corbeau freux","Corvus frugilegus","plus d'information"),
		("Pic épeichette","Dryobates minor","plus d'information"),
		("Pigeon biset","Columba livia","plus d'information"),
		("Roitelet triple-bandeau","Regulus ignicapilla","plus d'information"),
		("Gallinule poule-d'eau","Gallinula chloropus","plus d'information"),
		("Mésange boréale","Poecile montanus","plus d'information"),
		("Grive mauvis","Turdus iliacus","plus d'information"),
		("Martin-pêcheur","Alcedo atthis","plus d'information"),
		("Grive draine","Turdus viscivorus","plus d'information"),
		("Fauvette à tête noire","Sylvia atricapilla","plus d'information"),
		("Grande aigrette","Ardea alba","plus d'information"),
		("Pic mar","Dendrocoptes medius","plus d'information"),
		("Canard colvert","Anas platyrhynchos","plus d'information"),
		("Pouillot véloce","Phylloscopus collybita","plus d'information"),
		("Chevêche d'Athéna","Athene noctua","plus d'information"),
		("Effraie des clochers","Tyto alba","plus d'information"),
		("Chouette hulotte","Strix aluco","plus d'information"),
		("Rougequeue noir","Phoenicurus ochruros","plus d'information"),
		("Linotte mélodieuse","Linaria cannabina","plus d'information"),
		("Bec-croisé des sapins","Loxia curvirostra","plus d'information"),
		("Jaseur boréal","Bombycilla garrulus","plus d'information"),
		("Perdrix grise","Perdix perdix","plus d'information"),
		("Pic noir","Dryocopus martius","plus d'information"),
		("Bergeronnette des ruisseaux","Motacilla cinerea","plus d'information"),
		("Serin cini","Serinus serinus","plus d'information"),
		("Pigeon colombin","Columba oenas","plus d'information"),
		("Hibou moyen-duc","Asio otus","plus d'information"),
		("Sizerin cabaret","Acanthis cabaret","plus d'information"),
	)
